# Generated by Django 6.0.5 on 2026-06-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_usergoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='user',
        ),
    ]
