# Generated by Django 6.0.6 on 2026-07-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_delete_usergoal_alter_foodentry_user'),
        ('tracker', '0004_usergoal_user_alter_foodentry_user'),
    ]

    operations = [
    ]
