# Generated by Django 6.0.6 on 2026-07-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_merge_20260702_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
